name: AuroraUniverse
version: 0.2.1.0
main: ru.etysoft.aurorauniverse.AuroraUniverse
softdepend: [PlaceholderAPI, Citizens]
depend: [EasyPluginCore]
api-version: 1.13
author: karlov_m
description: AuroraUniverse is a good plugin that provides a system of cities, wars, trade, countries and various ranks. A good, and most importantly confident solution for moving from Towny.
website: etysoft.ru

commands:
  aurorauniverse:
    description: Main plugin command
    aliases: [aun]
  auntown:
    description: Town command
    aliases: [town, t]
  aunnation:
    description: Nation command
    aliases: [n, nation]
  auneco:
    description: Town command
    aliases: [money]
  aunchat:
    description: Chat change command
    aliases: [chat, tc, lc, g, local, global]
permissions:

  ########################################
  #                                      #
  #         Aurora Plugin Perms          #
  #                                      #
  ########################################

  aun.admin:
    default: op
    children:
      aun.info: true
      aun.edittown: true
    description: Allows all commands

  aun.info:
    default: op
    description: Get information

  aun.edittowns:
    default: op
    description: Bypass every check

  ########################################
  #                                      #
  #          Town permissions            #
  #                                      #
  ########################################

  town.*:
    default: op
    children:
      town.create: true
      town.delete: true
      town.residents.invite: true
      town.residents.kick: true
      town.leave: true
      town.deposit: true
      town.withdraw: true
      town.claim: true
      town.unclaim: true
      town.edit: true
      town.rename: true
      town.teleport.spawn: true
      town.teleport.outpost: true
      town.set.*: true
      town.toggle.*: true
      town.region.*: true

    description: Allows all commands

  town.create:
    default: op
    description: Create a town

  town.rename:
    default: op
    description: Rename a town

  town.delete:
    default: op
    description: Delete a town

  town.residents.invite:
    default: op
    description: Invite new residents

  town.residents.kick:
    default: op
    description: Kick a resident

  town.leave:
    default: op
    description: Leave town

  town.deposit:
    default: op
    description: Withdraw money into the town's bank

  town.withdraw:
    default: op
    description: Withdraw money from the town's bank

  town.claim:
    default: op
    description: Withdraw money from the town's bank

  town.unclaim:
    default: op
    description: Withdraw money from the town's bank

  ############
  #   Edit   #
  ############

  town.edit:
    default: op
    description: All block operations in town
    children:
      town.regions.build: true
      town.regions.destroy: true
      town.destroy: true
      town.build: true

  town.regions.build:
    default: op
    description: Can place blocks in towns but can't in player's regions

  town.regions.destroy:
    default: op
    description: Can break blocks in towns but can't in player's regions

  town.destroy:
    default: op
    description: Can break blocks in town

  town.build:
    default: op
    description: Can place blocks in town

  ##################
  #    Teleport    #
  ##################

  town.teleport.spawn:
    default: op
    description: Teleport on town spawn

  town.teleport.outpost:
    default: op
    description: Teleport on town spawn


  teleport.towns:
    default: op
    description: Teleport on towns

  #############
  #    Set    #
  #############

  town.set.*:
    default: op
    description: Set all
    children:
      town.set.spawn: true
      town.set.perms: true
      town.set.group: true
      town.set.tax: true

  town.set.spawn:
    default: op
    description: Set town's spawn

  town.set.perms:
    default: op
    description: Set town's permissions

  town.set.tax:
    default: op
    description: Set town's tax

  town.set.group:
    default: op
    description: Give group to player

  town.set.mayor:
    default: op
    description: Change mayor of town
  ################
  #    Region    #
  ################

  town.region.*:
    default: op
    description: Toggle all in town
    children:
      town.region.give: true
      town.region.reset: true
      town.region.addmember: true
      town.region.kick: true
      town.region.bypass: true
      town.region.info: true
      town.region.pvp: true

  town.region.give:
    default: op
    description: Give region to player

  town.region.info:
    default: op
    description: Give information about region to player

  town.region.bypass:
    default: op
    description: Bypass regions

  town.region.reset:
    default: op
    description: Reset region to town owned

  town.region.pvp:
    default: op
    description: Toggle pvp in region

  town.region.addmember:
    default: op
    description: Add member to region

  town.region.kick:
    default: op
    description: Kick member from region

  ################
  #    Toggle    #
  ################

  town.toggle.*:
    default: op
    description: Toggle all in town
    children:
      town.toggle.pvp: true
      town.toggle.fire: true
      town.toggle.mobs: true
      town.toggle.explosions: true

  town.toggle.pvp:
    default: op
    description: Toggle PvP in town

  town.toggle.mobs:
    default: op
    description: Toggle monsters in town

  town.toggle.fire:
    default: op
    description: Toggle fire in town

  town.toggle.explosions:
    default: op
    description: Toggle explotions in town

  ########################################
  #                                      #
  #               Economy                #
  #                                      #
  ########################################

  auneconomy.pay:
    default: op
    description: Pay someone from your balance

  auneconomy.give:
    default: op
    description: Give money to someone from air

  auneconomy.take:
    default: op
    description: Take money from someone

  auneconomy.balance:
    default: op
    description: Show your balance

  ########################################
  #                                      #
  #               Nation                 #
  #                                      #
  ########################################
  nation.*:
    default: op
    description: Toggle all in town
    children:
      nation.create: true
      nation.invite: true
      nation.accept: true
      nation.kick: true
      nation.leave: true
      nation.delete: true
      nation.tax: true
      nation.teleport: true
  nation.create:
    default: op
    description: Create nation
  nation.teleport:
    default: op
    description: Teleport on town's spawn
  nation.invite:
    default: op
    description: Invite town into nation
  nation.tax:
    default: op
    description: Allows to set tax
  nation.accept:
    default: op
    description: Accept invite
  nation.kick:
    default: op
    description: Kick town from nation
  nation.leave:
    default: op
    description: Leave from nation
  nation.delete:
    default: op
    description: Delete nation


    ########################################
    #                                      #
    #                Chat                  #
    #                                      #
    ########################################
  aunchat.*:
    default: op
    description: Toggle all in town
    children:
      nation.color: true

  aunchat.color:
    default: op
    description: Delete nation