name: AuroraUniverse
version: 0.1.1.0
main: ru.etysoft.aurorauniverse.AuroraUniverse
api-version: 1.13
author: karlov_m
description: AuroraUniverse is a good plugin that provides a system of cities, wars, trade, countries and various ranks. A good, and most importantly confident solution for moving from Towny.
website: etysoft.ru
commands:
  aurorauniverse:
    description: Main plugin command
    aliases: [aun]
  auntown:
    description: Town command
    aliases: [town, t]
  auneco:
    description: Town command
    aliases: [money]
permissions:

  ########################################
  #                                      #
  #         Aurora Plugin Perms          #
  #                                      #
  ########################################

  aun.admin:
    default: op
    children:
      aun.info: true
      aun.edittown: true
    description: Allows all commands

  aun.info:
    default: op
    description: Get information

  aun.edittowns:
    default: op
    description: Bypass every check

  ########################################
  #                                      #
  #          Town permissions            #
  #                                      #
  ########################################

  town.*:
    default: op
    children:
      town.create: true
      town.delete: true
      town.residents.invite: true
      town.residents.kick: true
      town.leave: true
      town.deposit: true
      town.withdraw: true
      town.claim: true
      town.unclaim: true
      town.edit: true
      town.teleport.spawn: true
      town.set.*: true
      town.toggle.*: true

    description: Allows all commands

  town.create:
    default: op
    description: Create a town

  town.delete:
    default: op
    description: Delete a town

  town.residents.invite:
    default: op
    description: Invite new residents

  town.residents.kick:
    default: op
    description: Kick a resident

  town.leave:
    default: op
    description: Leave town

  town.deposit:
    default: op
    description: Withdraw money into the town's bank

  town.withdraw:
    default: op
    description: Withdraw money from the town's bank

  town.claim:
    default: op
    description: Withdraw money from the town's bank

  town.unclaim:
    default: op
    description: Withdraw money from the town's bank

  ############
  #   Edit   #
  ############

  town.edit:
    default: op
    description: All block operations in town
    children:
      town.regions.build: true
      town.regions.destroy: true
      town.destroy: true
      town.build: true

  town.regions.build:
    default: op
    description: Can place blocks in towns but can't in player's regions

  town.regions.destroy:
    default: op
    description: Can break blocks in towns but can't in player's regions

  town.destroy:
    default: op
    description: Can break blocks in town

  town.build:
    default: op
    description: Can place blocks in town

  ##################
  #    Teleport    #
  ##################

  town.teleport.spawn:
    default: op
    description: Teleport on town spawn

  #############
  #    Set    #
  #############

  town.set.*:
    default: op
    description: Set all
    children:
      town.set.spawn: true
      town.set.perms: true

  town.set.spawn:
    default: op
    description: Set town's spawn

  town.set.perms:
    default: op
    description: Set town's permissions

  ################
  #    Toggle    #
  ################

  town.toggle.*:
    default: op
    description: Toggle all in town
    children:
      town.toggle.pvp: true

  town.toggle.pvp:
    default: op
    description: Toggle PvP in town

  town.toggle.fire:
    default: op
    description: Toggle fire in town

  ########################################
  #                                      #
  #              Economy                 #
  #                                      #
  ########################################

  auneconomy.pay:
    default: op
    description: Pay someone from your balance

  auneconomy.give:
    default: op
    description: Give money to someone from air

  auneconomy.take:
    default: op
    description: Take money from someone

  auneconomy.balance:
    default: op
    description: Give money to someone from air

