name: AuroraUniverse
version: @version@
main: ru.etysoft.aurorauniverse.AuroraUniverse
api-version: 1.13
authors: [karlov_m]
description: AuroraUniverse is a good plugin that provides a system of cities, wars, trade, countries and various ranks. A good, and most importantly confident solution for moving from Towny.
website: etysoft.ru
